--- !ruby/object:OpenWFE::Environment 
attributes: 
environment_id: 
fei: !ruby/OpenWFE::FlowExpressionId 
  s: (fei 0.9.20 engine ee ee 0 0 environment 0)
parent_id: 
updated_at: 2009-07-21 15:21:06.863297 +09:00
variables: {}

