
smartmail:
  smtp_server: smtp.gmail.com
  smtp_server_port: 587
  imap_server: imap.gmail.com
  imap_server_port: 993
  from_address: smart.mailflow@gmail.com
  user_name: smart.mailflow@gmail.com
  user_password:  gks-smartmail
  spreadsheet_key: 0Aiz991afIPnTdGRjZFJ0RTJBdXhHQlI3T1Z6V0RDaHc
  store_name: smartmail
  deal_with_tag: 受け付け
  calendars:
    - name: default
      ident: "smart.mailflow%40gmail.com"
      sheet_key: "0Aiz991afIPnTdGRjZFJ0RTJBdXhHQlI3T1Z6V0RDaHc"
    - name: "事務員1"
      ident: "tcd4k7ud81ns2iulfco0612it4%40group.calendar.google.com"
      sheet_key: "0Aiz991afIPnTdGRjZFJ0RTJBdXhHQlI3T1Z6V0RDaHc"
    - name: "事務員2"
      ident: "ujpr1df0jj8gm5f9pjuq63l4rs%40group.calendar.google.com"
      sheet_key: "0Aiz991afIPnTdGRjZFJ0RTJBdXhHQlI3T1Z6V0RDaHc"
    - name: "事務員3"
      ident: "tcd4k7ud81ns2iulfco0612it4%40group.calendar.google.com"
      sheet_key: "0Aiz991afIPnTdGRjZFJ0RTJBdXhHQlI3T1Z6V0RDaHc"
    - name: "吉井あさ"
      ident: "iio9j7fkgautvu00h4gb34q360%40group.calendar.google.com"
      sheet_key: "tJ3XXJm__EvXe5LESmrFUWw"
    - name: "孫コウ"
      ident: "689ssgmohv2drlu4kjl3bgfv14%40group.calendar.google.com"
      sheet_key: "tP3xzVaG2bOL0QHKgJ-KMGQ"
    - name: "王リンキ"
      ident: "mf0lj9d0fdv6gem0mjthi2ub0k%40group.calendar.google.com"
      sheet_key: "tlx3IJZenlg9IJpCa_m84gg"
    - name: "大塚絵理" 
      ident: "dbcarmo3aama5c94i5ltfb0ieg%40group.calendar.google.com"
      sheet_key: "tLYSh6zUyfBkTeAKxrm1q-Q"
    - name: "河原奈生"
      ident: "85qa791i9moa37c6s12o7vaieo%40group.calendar.google.com"
      sheet_key: "t1dvzLThi88PoDhprUsmASQ"
    - name: "錦織聡一"
      ident: "kld8in9usgnkr8s30o2v58n1vs%40group.calendar.google.com"
      sheet_key: "tyJryK3zD6SR9Ua4QoD_y7g"
    - name: "佐瀬毅"
      ident: "6jsjf71pi1vestdrh9kohslekk%40group.calendar.google.com"
      sheet_key: "tu_JBxwTNeNQ5ytPEvNyx3A"
    - name: "小川洋史"
      ident: "e6m69a6pql7vtkb9co7soteiuc%40group.calendar.google.com"
      sheet_key: "tYnpLuioUBFToGImld9FEjg"
    - name: "原田明典"
      ident: "alsdcfldnmpgtcb3p1gu0bqp78%40group.calendar.google.com"
      sheet_key: "tjwuwSwqDtzwkzxam9PWBbA"
    - name: "井川甲作"
      ident: "u1rojji66pnponfa206vj9jdfs%40group.calendar.google.com"
      sheet_key: "tgQTz-7ss746yLYj5kTQSoQ"
    - name: "樋口量"
      ident: "a5ob7mg2bboragadi4sb85mb4s%40group.calendar.google.com"
      sheet_key: "tHqqaUCCnSVGb-RwVxzqTEw"
    - name: "浜口斉周"
      ident: "qhmqi3u7f23nbv2h9o2mcocujc%40group.calendar.google.com"
      sheet_key: "t-yfuYsJQesfHHF9RHNhB3Q"
    - name: "中村人哉"
      ident: "hlb0u0fr6tg0aecn28flqi9554%40group.calendar.google.com"
      sheet_key: "tZiu7D3sxwltqEgq51LiB8Q"
    - name: "比嘉邦彦"
      ident: "dc2p9v86g51qp17s877boisifg%40group.calendar.google.com"
      sheet_key: "ty73D8rTSBWeHMt-L4Lj2HA"
  reminder:
    header: "【reminder】"
    contents: "下記の内容のreminderです。\n"
