
smartmail:
  smtp_server: smtp.gmail.com
  smtp_server_port: 587
  imap_server: imap.gmail.com
  imap_server_port: 993
  from_address: smart.mailflow@gmail.com
  user_name: smart.mailflow@gmail.com
  user_password:  gks-smartmail
  spreadsheet_key: tdcdRtE2AuxGBR7OVzWDChw
  store_name: smartmail
  deal_with_tag: 受け付け
  reminder:
    header: "【reminder】"
    contents: "下記の内容のreminderです。\n"
