# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# On Mac OS X:
#   sudo gem install mysql -- --with-mysql-dir=/usr/local/mysql
# On Mac OS X Leopard:
#   sudo env ARCHFLAGS="-arch i386" gem install mysql -- --with-mysql-config=/usr/local/mysql/bin/mysql_config
#       This sets the ARCHFLAGS environment variable to your native architecture

development:
  adapter: mysql
  encoding: utf8
  database: rw2_development
  username: root
  password:
  reconnect: true
  host: localhost
  pool: 30

test:
  adapter: mysql
  encoding: utf8
  database: rw2_test
  username: root
  password:
  reconnect: true
  host: localhost
  pool: 30

production:
  adapter: mysql
  encoding: utf8
  database: rw2_production
  username: root
  password: 
  reconnect: true
  host: localhost
  pool: 30
